.github/workflows/cms-deploy.yml

```
[ ] Bugfix
[ ] Feature
[ ] Release
[x] CI related changes
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: fix cms ci

---

.github/workflows/cms-deploy.yml

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

fix: cms ci

---

.github/workflows/cms-deploy.yml

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: fucker test cms ci i need to sleeeep

---

.github/workflows/assets.yml
.github/workflows/web-deploy.yml

```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: please work

---

.github/workflows/assets.yml
.github/workflows/web-deploy.yml

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: idk i did nothing

---

.github/workflows/web-deploy.yml
README.md
docs/environment-variables.md
docs/todo.md

```
[ ] Bugfix
[ ] Feature
[ ] Release
[x] CI related changes
[x] Documentation content changes
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: remove unused cache option from FTP deployment in workflow

---

.github/workflows/web-deploy.yml
.github/workflows/web-production.yml
.github/workflows/web-staging.yml

```
[ ] Bugfix
[ ] Feature
[ ] Release
[x] CI related changes
[ ] Tests
[ ] Other
```
Closes #
-
N/A

fix(ci): remove deploy_path input and usage from web deploy workflows

---

.github/workflows/web-deploy.yml
.github/workflows/web-production.yml
.github/workflows/web-staging.yml
apps/assets/.htaccess

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

ci: fix and release 

---

apps/web/src/components/layout/header.tsx
apps/web/src/components/layout/mobile-header.tsx

```
[ ] Bugfix
[] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

feat: update SBI fee portal link to new corpID 6862046

---

apps/web/src/app/admission/btech/admissionLinkData.ts

- Added new quick link for PM Vidya Laxmi Education Loan Scheme from Canara Bank
- Link points to /docs/PM_VIDYA_LAXMI_EDUCATION_LOAN_-CANARA_BANK_FOR_IIIT_DHARWAD.pdf
- Positioned before FAQ's link for better visibility
```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

feat: add PM Vidya Laxmi Education Loan Scheme - Canara Bank quick link

---

apps/web/src/app/(home)/hero.tsx
apps/web/src/app/(home)/page.tsx

```
[ ] Bugfix
[ ] Feature
[ ] Release
[X] Code style update (formatting, local variables)
[ ] Tests
[ ] Other
```
Closes #
-
N/A

feat(web): fetch floating images with cache no-store for SSR

---

apps/web/src/data/registrar.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

fix: update Registrar name to Prof. (Dr.) Muruganantham Ponnusamy

---

apps/web/src/data/footer-links.ts

```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

feat(footer): add RTI link to INFORMATION section in footer

---

apps/web/src/components/layout/header.tsx
apps/web/src/components/layout/mobile-header.tsx
apps/web/src/data/navigation.ts

```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

Fix/rti link public disclosures (#52)

---

apps/web/src/app/(other)/released-soon/page.tsx
apps/web/src/data/footer-links.ts

feat(other): add Coming Soon page (/released-soon) for "Academic Calendar for First Year B.Tech"
feat(footer): New link for "Academic Calendar for First Year B.Tech"

feat(footer): add Coming Soon academic calendar for First Year link

---

apps/web/src/app/academics/programmes/page.tsx

feat(programmes): Added a new link element ("Academic Calendar 2025-26 for First Year B.Tech Students (August - November)") in /academics/programmes/ under the "More Resources" section

feat(programmes/page.tsx): Added link to First Year Academic Calendar

---

apps/web/src/app/(other)/faq/page.tsx

fixed the improper href routing issue in faq page in src/app/(other)/faq/page.tsx

fix(faq): corrected the href routes in src/app/(other)/faq/page.tsx

---

apps/web/src/app/(home)/hero.tsx
apps/web/src/app/admission/btech/admissionLinkData.ts
apps/web/src/app/placements/placement-stats.tsx

feat(admissions), feat(home) - added files in admission/btech and a new Quicklink in homepage

feat(admissions): added new files for admission, guidelines, vacancy list for CSAB

---

apps/web/src/app/(home)/hero.tsx
apps/web/src/app/admission/btech/admissionLinkData.ts

changed titles, reordered items

chore(admissions): update section titles and reorder items

---

apps/web/src/app/(home)/social-media.tsx
apps/web/src/components/layout/footer.tsx

- Updated footer Instagram link from iiit.dharwad to iiit.dharwad/
- Updated social media component Instagram link from iiitdharwad_ to iiit.dharwad/
- Ensures consistent Instagram URL across website components
```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A

fix: update Instagram URL to correct handle @iiit.dharwad

---

apps/cms/package.json
apps/web/src/data/footer-links.ts
apps/web/src/data/navigation.ts

feat(data): added new dropdown files under RTI

---

apps/web/src/app/(other)/RTI/page.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

fixed the issue with this page

fix(rti-disclosure): bug fix

---

apps/web/src/app/(other)/RTI/page.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

added sidebar nav, hardcoded data onto the file

feat(rti-disclosure): added schema and harcoded data for Organization and Function

---

apps/web/src/app/(other)/RTI/page.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

chore(rti-disclosure): added data for publicityAndPublicInterfaceData and budgetAndProgrammeData

---

apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

chore(rt-disclosure): added all data

---

apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx
apps/web/src/data/navigation.ts

added hyperlink feature for tabular data

feat(rti-disclosure): added hyperlink feature for tabular data

---

apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

added href feat for emails, links and data changes

feat(rti-disclosure): hyperlinks and data fix

---

apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

chore(rti-disclosures): data added in 1.13

---

apps/web/src/app/(home)/info-section.tsx

chore(info-section): welcome poster change

---

apps/web/src/app/(other)/RTI/rti-disclosure/TableDisplay.tsx
apps/web/src/app/(other)/RTI/rti-disclosure/page.tsx

chore(rti-disclosure): updated data

---

apps/web/src/app/placements/higher-studies-contact.tsx
apps/web/src/components/layout/header.tsx
apps/web/src/components/layout/mobile-header.tsx

new card component for CGC, Professor-In-Charge Prof. Vasudev Parvati in the contact section of /placements

chore(placements): added new card component in contact sec

---

apps/cms/src/sanity/schemas/generalInfo/JobCategory.ts
apps/cms/src/sanity/schemas/generalInfo/Jobs.ts
apps/cms/src/sanity/schemas/index.ts
apps/web/src/app/(institute)/careers/careers-page.tsx
apps/web/src/app/(institute)/careers/page.tsx
apps/web/src/sanity/lib/queries.ts
apps/web/src/sanity/types.ts

```
[ ] Bugfix
[x] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
Updated CMS Job categories and modifying careers page accordingly
-
N/A

feat: update CMS Jobs and web careers pages
